In [4]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install numpy


     ---------------------------------------- 14.8/14.8 MB 5.6 MB/s eta 0:00:00


Anaconda Prompt 창에서

conda install 패키지명

In [7]:
import numpy as np

In [12]:
a = [1,2,3]
b = np.array(a)

In [13]:
print(type(a))
print(type(b))
print(a)
print(b)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3]
[1 2 3]


In [22]:
array1 = b.copy()
array2 = np.array([4,5,6])
print('array1 type:', type(array1))
print(array1)
print(array2)
print(array1+array2)
array1[1]
print(array1.shape) # (,3)인데 튜플이라 ,가 뒤로 가서 (3,)

array1 type: <class 'numpy.ndarray'>
[1 2 3]
[4 5 6]
[5 7 9]
(3,)


In [31]:
# 2차원 np리스트
array2d = np.array([[1,2,3],[11,22,33]])
print('array2d의 type: ', type(array2d))
print(array2d)
print('array2d의 형태: ', array2d.shape)
print('array2d는 {0}차원'.format(array2d.ndim))
print(f'array2d는 {array2d.ndim}차원')

array2d의 type:  <class 'numpy.ndarray'>
[[ 1  2  3]
 [11 22 33]]
array2d의 형태:  (2, 3)
array2d는 2차원
array2d는 2차원


In [36]:
# 3차원 np리스트
array3d = np.array([[[1,2,3],[11,22,33]]]) # 1,2,3
print('array3d의 type: ', type(array3d))
print(array3d)
print('array3d의 형태: ', array3d.shape)
print('array3d는 {0}차원'.format(array3d.ndim))
print(f'array3d는 {array3d.ndim}차원')

array3d의 type:  <class 'numpy.ndarray'>
[[[ 1  2  3]
  [11 22 33]]]
array3d의 형태:  (1, 2, 3)
array3d는 3차원
array3d는 3차원


In [50]:
# ?를 활용한 함수 검색
# ?np.array
# ?np.ndim
# ?np.shape
# help를 통한 함수 검색
# help(np.ndim)
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [60]:
array3d = np.array([[[1,2,3],[11,22,33]]]) # 1,2,3
array3d_1 = np.array([[[11,22,33]]]) # 1,1,3
array3d_2 = np.array([[[11,22,33]],[[11,22,33]]]) # 2,1,3
print('array3d의 형태: ', array3d.shape)
print('array3d_1의 형태: ', array3d_1.shape)
print('array3d_2의 형태: ', array3d_2.shape)
print('array3d의 차원: ', array3d.ndim)
print('array3d_1의 차원: ', array3d_1.ndim)
print('array3d_2의 차원: ', array3d_2.ndim)
#(1,2,3)-> (1,1,3)으로 바꿔보기
#(1,2,3)-> (2,1,3)으로 바꿔보기

array3d의 형태:  (1, 2, 3)
array3d_1의 형태:  (1, 1, 3)
array3d_2의 형태:  (2, 1, 3)
array3d의 차원:  3
array3d_1의 차원:  3
array3d_2의 차원:  3


In [75]:
# 또 다른 용례
arr_test = np.array(
    [
        [1,2,3],
        [11,22,33,44]
    ])
print(arr_test.shape) #(2,) -->1차원으로 인식함

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## ndarray 편리하게 생성 - arrange, zeros, ones

### 1) arrange
시작값과 끝값을 지정해서 순차적인 배열 만들기

In [66]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [68]:
?np.arange

In [70]:
np.arange(start=1, stop=6)

array([1, 2, 3, 4, 5])

In [71]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

### 2)zeros
데이터 형태를 지정해서 만들 경우 0으로 우선 값을 채워두기 때문에

In [74]:
np.zeros((3,2), dtype='int32')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [83]:
zero_array = np.zeros((2,4), dtype='int32')
print(zero_array, zero_array.dtype, zero_array.shape)

[[0 0 0 0]
 [0 0 0 0]] int32 (2, 4)


### 3)ones

In [84]:
# ones로 1로 된 행렬을 생성
one_array = np.ones((3,2), dtype='float64')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [85]:
type(one_array)

numpy.ndarray

In [90]:
arr_test = np.arange(start=1, stop=11)
print(arr_test)
arr_test.reshape(2,5)
print(arr_test.reshape(2,5))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## reshape의 용례

In [91]:
seq_array = np.arange(start=1, stop=11)
seq_array.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## numpy의 dtype
**numpy는 서로 다른 종류의 데이터가 못 온다!** 
Numpy의 데이터 타입은 다 같은 타입으로 구성된다.

In [93]:
l2 = [1,2,'test']  # int와 str
# np.array를 활용하여 ndarray로 변환
np.array(l2)  # unicode11 문자를 의미

array(['1', '2', 'test'], dtype='<U11')

In [95]:
array_l2 = np.array(l2)
l3 = [1, 2, 5.5]  #int와 float
array_l3 = np.array(l3)
print(array_l3, array_l3.dtype) 
# numpy는 서로 다른 종류의 데이터가 못 온다.

[1.  2.  5.5] float64


In [99]:
# dtype의 상호 변환
array_int = np.array([1,3,5])
array_float = array_int.astype('float64')  # 형변환

# array_float -> array_int2
array_int2 = array_float.astype('int32')

# 자료에 따른 버림 현상
array_float2 = np.array([1.1, 2.2, 3.6])
array_float2.astype('int32')

array([1, 2, 3])