# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
*넘파이에서 ndarray내의 일부 데이터 셋이나 특정 데이터만을 선택할 수 있도록 인덱싱
- 1. 특정한 데이터만 추출

- 2. 슬라이싱(Slicing)

- 3. 팬시 인덱싱(Fancy Indexing)

- 4. 불리언 인덱싱(Boolean Indexing)


넘파이는 열을 기준으로 본다. (텐서플로우는 행,열...)

In [1]:
import numpy as np

## 1. 특정한 데이터만 추출

In [10]:
# 1~9까지 1차원 ndarray생성 - np.arange
array1 = np.arange(1,10)  # float으로 하려면 dtype='float64'
print(array1)
value = array1[-1]
print(f'value:{value}, type:{type(value)}')

[1 2 3 4 5 6 7 8 9]
value:9, type:<class 'numpy.int32'>


In [20]:
# array1을 2차원으로 변형
array1d = array1.copy()
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
array2d[0][0],array2d[0][1],array2d[1][0],array2d[2][2]

(1, 2, 4, 9)

In [26]:
array2d[0,0],array2d[0,1],array2d[1,0],array2d[-1,-1]

(1, 2, 4, 9)

## 2. 슬라이싱(Slicing)¶

In [46]:
print(array2d)
print(f'\narray2d[0:3, 0:2]:\n',array2d[0:3, 0:2])
print(f'\narray2d[0:2, 0:2]:\n',array2d[0:2, 0:2])
print(f'\narray2d[1:, 0:3]:\n',array2d[1:, 0:3])
print(f'\narray2d[1:, :]:\n',array2d[1:, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:3, 0:2]:
 [[1 2]
 [4 5]
 [7 8]]

array2d[0:2, 0:2]:
 [[1 2]
 [4 5]]

array2d[1:, 0:3]:
 [[4 5 6]
 [7 8 9]]

array2d[1:, :]:
 [[4 5 6]
 [7 8 9]]


In [59]:
# question 1
print(f'array2d(:2, 0):\n', array2d[:2, 0])
print(f'array2d(:2, 0:1):\n', array2d[:2, 0:1])

array2d(:2, 0):
 [1 4]
array2d(:2, 0:1):
 [[1]
 [4]]


## 3. 팬시 인덱싱(Fancy Indexing)

In [75]:
print(array2d)
# 3과 6을 1차원으로 가져오자
print(array2d[[0,1],2])
print(array2d[[0,2],2:])
print(array2d[0:2,2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[3]
 [9]]
[[3]
 [6]]
