# Boolean indexing

In [1]:
import numpy as np

In [19]:
array1d = np.arange(start=1, stop=10)
print(array1d)

#boolean indexing
print(array1d>5)
print([array1d>5])
print(array1d[array1d>5])  # True만 출력

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[array([False, False, False, False, False,  True,  True,  True,  True])]
[6 7 8 9]


In [11]:
for i in array1d:
    if i>5:
        print(i, end= ' ')
    else:
        pass

6 7 8 9 

In [14]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array1d[boolean_indexesexes]

array([6, 7, 8, 9])

## 행렬의 정렬 - sort()와 argsort()

In [20]:
org_array = np.array([3,1,9,5])
print('원본행렬:', org_array)

원본행렬: [3 1 9 5]


In [30]:
# 1. np.sort(ndarray)로 정렬 / 원본은 변함 없음
sort_array1 = np.sort(org_array)
print('np.sort()적용 후 원본행렬', org_array)
print('np.sort()적용 후 반환된 정렬행렬', sort_array1)

np.sort()적용 후 원본행렬 [1 3 5 9]
np.sort()적용 후 반환된 정렬행렬 [1 3 5 9]


In [31]:
# 2. ndarray.sort()로 정렬 / 원본 변함. None반환
sort_array2 = org_array.sort()
print('np.sort()적용 후 원본행렬', org_array)
print('np.sort()적용 후 반환된 정렬행렬', sort_array2)

np.sort()적용 후 원본행렬 [1 3 5 9]
np.sort()적용 후 반환된 정렬행렬 None


In [33]:
# 내림차순 정렬[::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬', sort_array1_desc)

내림차순 정렬 [9 5 3 1]


In [34]:
# end of file